/*
 * message_table.h
 *
 *  Created on: 9 déc. 2018
 *      Author: Moritz Laim
 */

#ifndef SOURCE_MESSAGE_TABLE_H
#define SOURCE_MESSAGE_TABLE_H

#define ECU		0
#define MOTOR	1
#define SENSOR	2



//CAN messages
#define NO_REP					0
#define SCM_PERIODS				100 //ms	smallest common multiplier of all periods

enum ECU_messages{SPEED_SETPOINT, TORQUE_SETPOINT, ECU_STATUS,
					CONTROL, ECU_ERROR, ECU_REQUEST, BMS_CONTACTOR} ;
enum Motor_messages{SPEED_VALUE, TORQUE_VALUE, MOTOR_STATUS} ;
enum Sensor_messages{BREAK_PEDAL, ACCELERATOR, STEERING, WHEEL_SPEED, ACCELERATION,
						ENVIRONMENT, COCKPIT, BMS_EVENTS, SENEOR_STATUS,
						SENSOR_ERROR, SENOR_REQUEST} ;

#define SETPOINT_ID  			0x181
#define SETPOINT_LENGTH 		3
#define SETPOINT_PERIOD 		1
#define ECU_STATUS_ID 			0x3D0
#define ECU_STATUS_LENGTH 		1
#define ECU_STATUS_PERIOD 		100
#define CONTROL_ID				0x100
#define CONTROL_LENGTH 			1
#define CONTROL_PERIOD 			NO_REP
#define ECU_ERROR_ID			0x101
#define ECU_ERROR_LENGTH 		1
#define ECU_ERROR_PERIOD 	 	NO_REP
#define ECU_REQUEST_ID			0x111
#define ECU_REQUEST_LENGTH 		1
#define ECU_REQUEST_PERIOD 		NO_REP
#define BMS_CONTACTOR_ID		0x331
#define BMS_CONTACTOR_LENGTH 	1
#define BMS_CONTACTOR_PERIOD 	NO_REP

#define MOTOR_SEND_ID 			0x27F
#define SPEED_VALUE_LENGTH 		3
#define SPEED_VALUE_PERIOD 		10
#define TORQUE_VALUE_LENGTH 	3
#define TORQUE_VALUE_PERIOD 	10
#define MOTOR_STATUS_LENGTH 	5
#define MOTOR_STATUS_PERIOD 	100

#define BREAK_PEDAL_ID 			0x1B0
#define BREAK_PEDAL_LENGTH 		2
#define BREAK_PEDAL_PERIOD 		1
#define ACCELERATOR_ID 			0x1B1
#define ACCELERATOR_LENGTH 		2
#define ACCELERATOR_PERIOD 		1
#define STEERING_ID 			0x1F0
#define STEERING_LENGTH 		2
#define STEERING_PERIOD 		10
#define WHEEL_SPEED_ID 			0x1F1
#define WHEEL_SPEED_LENGTH 		8
#define WHEEL_SPEED_PERIOD 		10
#define ACCELERATION_ID 		0x1F2
#define ACCELERATION_LENGTH 	4
#define ACCELERATION_PERIOD 	10
#define ENVIRONMENT_ID 			0x2C0
#define ENVIRONMENT_LENGTH 		2
#define ENVIRONMENT_PERIOD 		50
#define COCKPIT_ID 				0x2C1
#define COCKPIT_LENGTH 			2
#define COCKPIT_PERIOD 			10
#define BMS_EVENTS_ID			0x335
#define BMS_EVENTS_LENGTH 		2
#define BMS_EVENTS_PERIOD 		10
#define SENEOR_STATUS_ID 		0x3D1
#define SENEOR_STATUS_LENGTH 	1
#define SENEOR_STATUS_PERIOD 	100
#define SENSOR_ERROR_ID 		0x102
#define SENSOR_ERROR_LENGTH 	2
#define SENSOR_ERROR_PERIOD 	NO_REP
#define SENOR_REQUEST_ID 		0x112
#define SENOR_REQUEST_LENGTH 	2
#define SENOR_REQUEST_PERIOD 	NO_REP

//UART messages
enum EcuMEssagesR{ECU_CONFIG_U};
enum MotorMessagesS{SPEED_SETPOINT_U, TORQUE_SETPOINT_U } ;
enum MotorMessagesR{MOTOR_CONFIG_U, TRUE_MOTOR_SPEED_U,TRUE_MOTOR_TORQUE_U} ;
enum SensorMessagesS{STEERING_ANGLE_U}  ;
enum SensorMessagesR{SENSOR_CONFIG_U, TRUE_SPEED_U, ACCELERATION_U, PEDALS_U,BUTTONS_U,ENVIRONMENT_U, STEERING_U};

enum ECUSendId{SYSTEM_STATE_ID_U = 0x80A2} ;
enum MotorSendId{SPEED_SETPOINT_ID_U = 0x80C9,
				 TORQUE_SETPOINT_ID_U =0x80CD} ;
enum SensorSendId{STEERING_ANGLE_ID_U=0x80E7};

#define SYSTEM_STATE_LENTH_U  		1

#define SPEED_SETPOINT_LENGTH_U		2
#define TORQUE_SETPOINT_LENGTH_U	2

#define STEERING_ANGLE_LENGTH_U		2

#define ECU_CONFIG_ID_U				0xA0
#define ECU_CONFIG_LENGHT_U			1
#define PARAM_ID_U					0xA1
#define PARAM_LENGTH_U				1

#define MOTOR_CONFIG_ID_U				0xC0
#define MOTOR_CONFIG_LENGTH_U			1
#define TRUE_MOTOR_SPEED_ID_U			0xC1
#define TRUE_MOTOR_SPEED_LENGTH_U		2
#define TRUE_MOTOR_TORQUE_ID_U		0xC5
#define TRUE_MOTOR_TORQUE_LENGTH_U	2

#define SENSOR_CONFIG_ID_U 			0xE0
#define SENSOR_CONFIG_LENGTH_U		1
#define TRUE_SPEED_ID_U				0xE1
#define TRUE_SPEED_LENGTH_U			8
#define ACCELERATION_ID_U			0xE2
#define ACCELERATION_LENGTH_U			6
#define PEDALS_ID_U					0xE3
#define PEDALS_LENGTH_U				4
#define BUTTONS_ID_U					0xE4
#define BUTTONS_LENGTH_U				1
#define ENVIRONMENT_ID_U				0xE5
#define ENVIRONMENT_LENGTH_U			2
#define STEERING_ID_U					0xE6
#define STEERING_LENGTH_U				2

#endif /* SOURCE_MESSAGE_TABLE_H */
